"use strict";

/**
 * Business role-play trial pack #1 — NOT yet wired into the live seed.
 * Category "business" requires the conversation-prompt category enum migration
 * (already applied). Distinct from existing "career" scenarios: this pack is
 * company-to-company / professional-deal-making, not personal workplace growth.
 * Review before merging into ROLE_PLAY_SCENARIOS in speaking-content-catalog.js.
 */

const { rolePlay } = require("../speaking-content-catalog");

const BUSINESS_PACK_01 = [
  rolePlay(
    "Negotiating a Startup Investment",
    "Pitch your startup to an angel investor. Explain the problem, your solution, answer difficult questions, and negotiate funding.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Founder",
      tutorRole: "Investor",
      iconKey: "work",
      order: 65,
      suggestedVocabulary: ["equity", "valuation", "market size", "investment", "profitability", "scalability"],
    },
  ),
  rolePlay(
    "Closing a B2B Sales Deal",
    "You're selling a software subscription to a procurement manager who is comparing you against a cheaper competitor. Justify the price and close the deal.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Sales representative",
      tutorRole: "Procurement manager",
      iconKey: "work",
      order: 66,
      suggestedVocabulary: ["quote", "discount", "contract term", "competitor", "value proposition", "sign off"],
    },
  ),
  rolePlay(
    "Handling a Product Recall Crisis",
    "A safety defect has been found in your company's flagship product. Explain the recall to a journalist without damaging trust further.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "PR director",
      tutorRole: "Journalist",
      iconKey: "campaign",
      order: 67,
      suggestedVocabulary: ["recall", "liability", "statement", "affected units", "remediation", "transparency"],
    },
  ),
  rolePlay(
    "Negotiating a Supplier Contract",
    "Your factory needs raw materials at a lower price. Push back on the supplier's quote while keeping the relationship intact.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Buyer",
      tutorRole: "Supplier representative",
      iconKey: "work",
      order: 68,
      suggestedVocabulary: ["bulk order", "unit price", "lead time", "payment terms", "minimum order quantity"],
    },
  ),
  rolePlay(
    "Presenting Quarterly Results to the Board",
    "Revenue missed target this quarter. Present the numbers to the board, explain what went wrong, and outline your recovery plan.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "CFO",
      tutorRole: "Board member",
      iconKey: "school",
      order: 69,
      suggestedVocabulary: ["quarterly results", "shortfall", "forecast", "margin", "recovery plan", "headwinds"],
    },
  ),
  rolePlay(
    "Resolving a Vendor Payment Dispute",
    "A vendor claims you owe them for an invoice you believe was already paid. Sort out the confusion and agree on next steps.",
    {
      difficultyLevel: "B1",
      category: "business",
      userRole: "Account manager",
      tutorRole: "Vendor",
      iconKey: "bank",
      order: 70,
      suggestedVocabulary: ["invoice", "outstanding balance", "payment proof", "due date", "reconcile"],
    },
  ),
  rolePlay(
    "Pitching a Merger to Company Leadership",
    "You believe merging with a competitor is the best path forward. Convince a skeptical CEO who fears losing control of the company.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Strategy advisor",
      tutorRole: "CEO",
      iconKey: "handshake",
      order: 71,
      suggestedVocabulary: ["merger", "synergy", "due diligence", "shareholder", "integration", "control"],
    },
  ),
  rolePlay(
    "Negotiating Terms with a Franchise Partner",
    "A potential franchisee wants to open a location in a new city but is asking for reduced franchise fees. Negotiate terms that work for both sides.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Franchisor representative",
      tutorRole: "Prospective franchisee",
      iconKey: "store",
      order: 72,
      suggestedVocabulary: ["franchise fee", "royalty", "territory", "brand standards", "term length"],
    },
  ),
  rolePlay(
    "Managing an Angry Investor Call",
    "The company just missed a major milestone. An early investor is furious and threatening to pull support. De-escalate and rebuild confidence.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Founder",
      tutorRole: "Investor",
      iconKey: "work",
      order: 73,
      suggestedVocabulary: ["milestone", "burn rate", "runway", "pivot", "accountability", "confidence"],
    },
  ),
  rolePlay(
    "Launching a Product at a Trade Show",
    "You're demoing a new product at a trade show booth. Explain what it does, answer questions, and try to get the visitor's contact details.",
    {
      difficultyLevel: "B1",
      category: "business",
      userRole: "Sales representative",
      tutorRole: "Trade show visitor",
      iconKey: "work",
      order: 74,
      suggestedVocabulary: ["demo", "features", "lead", "brochure", "follow up", "booth"],
    },
  ),
  rolePlay(
    "Discussing Layoffs with HR",
    "Budget cuts mean your department must lose two positions. Work through the criteria and process with HR before the announcement.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Department manager",
      tutorRole: "HR director",
      iconKey: "groups",
      order: 75,
      suggestedVocabulary: ["layoff", "severance", "restructuring", "headcount", "notice period", "criteria"],
    },
  ),
  rolePlay(
    "Negotiating a Joint Venture Agreement",
    "Your company wants to enter a foreign market through a joint venture. Agree on ownership split and responsibilities with a local partner.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Company representative",
      tutorRole: "Foreign business partner",
      iconKey: "handshake",
      order: 76,
      suggestedVocabulary: ["joint venture", "ownership stake", "local partner", "regulatory approval", "governance"],
    },
  ),
  rolePlay(
    "Responding to a Hostile Takeover Bid",
    "A rival firm has made an unsolicited bid to acquire your company. Discuss defense strategy with the board chair.",
    {
      difficultyLevel: "C2",
      category: "business",
      userRole: "CEO",
      tutorRole: "Board chair",
      iconKey: "gavel",
      order: 77,
      suggestedVocabulary: ["hostile takeover", "poison pill", "shareholder vote", "undervalued", "fiduciary duty"],
    },
  ),
  rolePlay(
    "Handling a Data Breach Disclosure",
    "Customer data has been exposed in a security breach. Explain what happened to a regulator and outline your remediation steps.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "CTO",
      tutorRole: "Regulator",
      iconKey: "shield",
      order: 78,
      suggestedVocabulary: ["data breach", "disclosure", "remediation", "compliance", "vulnerability", "encryption"],
    },
  ),
  rolePlay(
    "Pitching to a Venture Capital Panel",
    "Present your startup to a panel of three VCs, each with different concerns — growth, unit economics, and team. Handle their questions.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Founder",
      tutorRole: "VC panel",
      iconKey: "work",
      order: 79,
      suggestedVocabulary: ["unit economics", "traction", "runway", "term sheet", "due diligence", "growth rate"],
    },
  ),
  rolePlay(
    "Negotiating Freelance Rates with a Client",
    "A client loves your work but says your rate is too high for their budget. Negotiate a rate or scope that works for both of you.",
    {
      difficultyLevel: "B1",
      category: "business",
      userRole: "Freelancer",
      tutorRole: "Client",
      iconKey: "work",
      order: 80,
      suggestedVocabulary: ["hourly rate", "scope of work", "budget", "deliverable", "retainer"],
    },
  ),
  rolePlay(
    "Convincing a Client to Renew a Contract",
    "A client is considering switching to a competitor at renewal time. Show them the value you've delivered and win the renewal.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Account executive",
      tutorRole: "Client",
      iconKey: "work",
      order: 81,
      suggestedVocabulary: ["renewal", "churn", "value delivered", "competitor", "loyalty discount"],
    },
  ),
  rolePlay(
    "Discussing Exit Strategy with Co-founders",
    "One co-founder wants to sell the company; another wants to keep building. Work through the disagreement together.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Co-founder",
      tutorRole: "Co-founder",
      iconKey: "handshake",
      order: 82,
      suggestedVocabulary: ["exit strategy", "acquisition offer", "buyout", "vesting", "alignment"],
    },
  ),
  rolePlay(
    "Explaining a Budget Cut to a Department",
    "Company-wide cuts mean your department's budget is shrinking by 20%. Explain the decision to a team lead and discuss priorities.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Finance director",
      tutorRole: "Team lead",
      iconKey: "bank",
      order: 83,
      suggestedVocabulary: ["budget cut", "reallocate", "priorities", "cost center", "justify"],
    },
  ),
  rolePlay(
    "Managing a Supply Chain Delay with a Client",
    "A shipment is delayed by three weeks due to a port issue. Inform the client and manage their expectations.",
    {
      difficultyLevel: "B1",
      category: "business",
      userRole: "Operations manager",
      tutorRole: "Client",
      iconKey: "work",
      order: 84,
      suggestedVocabulary: ["shipment", "delay", "supply chain", "estimated arrival", "compensation"],
    },
  ),
  rolePlay(
    "Negotiating Equity in a New Partnership",
    "You and a potential business partner are forming a company together. Agree on how much equity each person should get.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Partner",
      tutorRole: "Prospective partner",
      iconKey: "handshake",
      order: 85,
      suggestedVocabulary: ["equity split", "vesting schedule", "sweat equity", "contribution", "ownership"],
    },
  ),
  rolePlay(
    "Handling a Whistleblower Complaint",
    "An employee has anonymously reported financial irregularities in another department. Discuss how to investigate discreetly.",
    {
      difficultyLevel: "C2",
      category: "business",
      userRole: "HR director",
      tutorRole: "Employee",
      iconKey: "shield",
      order: 86,
      suggestedVocabulary: ["whistleblower", "irregularity", "investigation", "confidentiality", "retaliation"],
    },
  ),
  rolePlay(
    "Pitching a Rebrand to Marketing Leadership",
    "You believe the company's brand feels outdated. Convince the CMO to approve a full rebrand, including the risks and timeline.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Brand consultant",
      tutorRole: "CMO",
      iconKey: "campaign",
      order: 87,
      suggestedVocabulary: ["rebrand", "brand identity", "target audience", "rollout", "risk"],
    },
  ),
  rolePlay(
    "Discussing an Acquisition Offer",
    "A larger company wants to acquire your business. Discuss the offer, valuation, and what happens to your team.",
    {
      difficultyLevel: "C2",
      category: "business",
      userRole: "Business owner",
      tutorRole: "Acquiring company representative",
      iconKey: "handshake",
      order: 88,
      suggestedVocabulary: ["acquisition", "valuation", "earn-out", "retention", "integration plan"],
    },
  ),
  rolePlay(
    "Negotiating Payment Terms After a Late Invoice",
    "A client is 60 days late paying an invoice. Call them to secure payment without damaging the relationship.",
    {
      difficultyLevel: "B1",
      category: "business",
      userRole: "Small business owner",
      tutorRole: "Client",
      iconKey: "bank",
      order: 89,
      suggestedVocabulary: ["overdue", "invoice", "payment plan", "late fee", "cash flow"],
    },
  ),
  rolePlay(
    "Presenting a Turnaround Plan to Investors",
    "The company has been losing money for two years. As the newly hired interim CEO, present your plan to fix it.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Interim CEO",
      tutorRole: "Investors",
      iconKey: "work",
      order: 90,
      suggestedVocabulary: ["turnaround", "restructuring", "cost reduction", "break even", "timeline"],
    },
  ),
  rolePlay(
    "Handling a Client Threatening to Cancel",
    "A key client is unhappy with recent service and threatening to cancel their contract. Save the relationship.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Account manager",
      tutorRole: "Client",
      iconKey: "work",
      order: 91,
      suggestedVocabulary: ["cancel", "service level", "escalate", "goodwill gesture", "retain"],
    },
  ),
  rolePlay(
    "Discussing Franchise Expansion into a New Country",
    "Your franchise wants to expand internationally for the first time. Discuss regulatory and cultural challenges with a local partner.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Franchise director",
      tutorRole: "Local partner",
      iconKey: "store",
      order: 92,
      suggestedVocabulary: ["expansion", "regulatory approval", "localization", "master franchise", "market entry"],
    },
  ),
  rolePlay(
    "Negotiating a Non-Compete Clause",
    "You're leaving your job to start a competing business. Negotiate the terms of your non-compete clause with HR.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Departing employee",
      tutorRole: "HR representative",
      iconKey: "gavel",
      order: 93,
      suggestedVocabulary: ["non-compete", "restrictive covenant", "duration", "geographic scope", "enforceable"],
    },
  ),
  rolePlay(
    "Explaining a Delay in Product Delivery",
    "A manufacturing issue means your buyer's order will be two weeks late. Explain the situation and offer a solution.",
    {
      difficultyLevel: "B1",
      category: "business",
      userRole: "Supplier",
      tutorRole: "Buyer",
      iconKey: "work",
      order: 94,
      suggestedVocabulary: ["delay", "manufacturing issue", "revised timeline", "partial shipment", "apology"],
    },
  ),
  rolePlay(
    "Pitching a Sponsorship Deal to a Brand",
    "You're organizing an event and want a well-known brand to sponsor it. Pitch the exposure and benefits they'd receive.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Event organizer",
      tutorRole: "Brand representative",
      iconKey: "campaign",
      order: 95,
      suggestedVocabulary: ["sponsorship", "exposure", "audience reach", "activation", "package"],
    },
  ),
  rolePlay(
    "Handling a Social Media Backlash as a Spokesperson",
    "A tweet from your company went viral for the wrong reasons. Respond to a reporter's questions about the backlash.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Spokesperson",
      tutorRole: "Reporter",
      iconKey: "campaign",
      order: 96,
      suggestedVocabulary: ["backlash", "viral", "damage control", "public statement", "accountability"],
    },
  ),
  rolePlay(
    "Discussing Succession Planning with the Founder",
    "The founder is retiring in a year and hasn't chosen a successor. Help them think through the options.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Consultant",
      tutorRole: "Founder",
      iconKey: "school",
      order: 97,
      suggestedVocabulary: ["succession planning", "successor", "transition period", "legacy", "internal candidate"],
    },
  ),
  rolePlay(
    "Negotiating Licensing Rights for a Product",
    "You want to license your patented technology to a manufacturer. Negotiate royalty rates and exclusivity terms.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Licensor",
      tutorRole: "Licensee",
      iconKey: "gavel",
      order: 98,
      suggestedVocabulary: ["licensing", "royalty", "exclusivity", "patent", "territory"],
    },
  ),
  rolePlay(
    "Convincing a Bank to Approve a Business Loan",
    "You need a loan to expand your small business. Convince a skeptical loan officer that your business plan is sound.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Business owner",
      tutorRole: "Loan officer",
      iconKey: "bank",
      order: 99,
      suggestedVocabulary: ["business loan", "collateral", "credit history", "interest rate", "repayment plan"],
    },
  ),
  rolePlay(
    "Managing a Cross-Department Budget Conflict",
    "Two departments both need the same limited budget for Q4. Mediate between finance and the department that wants funding.",
    {
      difficultyLevel: "B2",
      category: "business",
      userRole: "Finance manager",
      tutorRole: "Department head",
      iconKey: "bank",
      order: 100,
      suggestedVocabulary: ["budget conflict", "prioritize", "trade-off", "ROI", "fiscal year"],
    },
  ),
  rolePlay(
    "Discussing Outsourcing with Concerned Staff",
    "Management is considering outsourcing part of production overseas. Address staff concerns about job security honestly.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Operations manager",
      tutorRole: "Employee representative",
      iconKey: "groups",
      order: 101,
      suggestedVocabulary: ["outsourcing", "job security", "cost savings", "transition support", "transparency"],
    },
  ),
  rolePlay(
    "Pitching a Cost-Cutting Plan to Skeptical Executives",
    "You've identified $2M in potential savings, but executives worry it will hurt morale. Defend your plan.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Consultant",
      tutorRole: "Executive",
      iconKey: "work",
      order: 102,
      suggestedVocabulary: ["cost-cutting", "efficiency", "morale", "implementation", "projected savings"],
    },
  ),
  rolePlay(
    "Handling a Client's Ethical Concerns About a Project",
    "A client is uneasy about the environmental impact of a project you're managing for them. Address their concerns honestly.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Account manager",
      tutorRole: "Client",
      iconKey: "work",
      order: 103,
      suggestedVocabulary: ["ethical concern", "environmental impact", "sustainability", "trade-off", "compliance"],
    },
  ),
  rolePlay(
    "Negotiating Exclusive Distribution Rights",
    "A distributor wants exclusive rights to sell your product in their region. Decide what to ask for in return.",
    {
      difficultyLevel: "C1",
      category: "business",
      userRole: "Manufacturer",
      tutorRole: "Distributor",
      iconKey: "handshake",
      order: 104,
      suggestedVocabulary: ["exclusive distribution", "territory", "minimum volume", "exclusivity period", "renewal"],
    },
  ),
];

module.exports = { BUSINESS_PACK_01 };
