const MACHINE_ANSWER_HANDICAP = 0.05;
const PARENTS_EMAILS_MAX_LENGTH = 4;
const DEFAULT_TIMEZONE = "Europe/Berlin";

module.exports = {
  MACHINE_ANSWER_HANDICAP,
  PARENTS_EMAILS_MAX_LENGTH,
  DEFAULT_TIMEZONE,
};
